name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: gw-physics-and-ligo
          root_file: main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: gw-physics-and-ligo/main.pdf
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest PDF"
          files: |
            gw-physics-and-ligo/main.pdf
